# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f81884e01c19c5caedb976a1a8a3e306bf8a9853762eb9c194fd888442aea4f8de666eff1e4236db3a1710f75380a40c6fb47520a9de84bc3601584c80a3d48

test:
  secret_key_base: ffae918320fc7325534825306abbfd21a7b0c9fe055787b2f110351ca50c5fe7a2c4190f46a18460216ad3dec43b95e64edd4fe9b544d921a05d1054664a4565

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
